/* eslint-disable */
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: any; output: any };
  /** Represents untyped JSON */
  JSON: { input: any; output: any };
};

export type Ability = {
  __typename: 'Ability';
  canApproveBrands: Scalars['Boolean']['output'];
  canCreateProjectPromotions: Scalars['Boolean']['output'];
  canUpdateTagCategories: Scalars['Boolean']['output'];
  canUpdateTags: Scalars['Boolean']['output'];
};

/** Autogenerated input type of AcceptBrandMembershipInvitation */
export type AcceptBrandMembershipInvitationInput = {
  brandId: Scalars['ID']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  invitationToken: Scalars['String']['input'];
};

/** Autogenerated return type of AcceptBrandMembershipInvitation. */
export type AcceptBrandMembershipInvitationPayload = {
  __typename: 'AcceptBrandMembershipInvitationPayload';
  brandMembership: BrandMembership;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of ApproveBrand */
export type ApproveBrandInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of ApproveBrand. */
export type ApproveBrandPayload = {
  __typename: 'ApproveBrandPayload';
  brand: Brand;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

export type Brand = {
  __typename: 'Brand';
  approved?: Maybe<Scalars['Boolean']['output']>;
  brandMemberships: Array<BrandMembership>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  creator?: Maybe<User>;
  currentUserCanCreateProjects: Scalars['Boolean']['output'];
  currentUserCanEdit: Scalars['Boolean']['output'];
  currentUserCanManageMemberships: Scalars['Boolean']['output'];
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  projects: ProjectConnection;
  slug: Scalars['String']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
  users: Array<User>;
};

export type BrandProjectsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};

export type BrandAttributes = {
  description?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

/** The connection type for Brand. */
export type BrandConnection = {
  __typename: 'BrandConnection';
  /** A list of edges. */
  edges: Array<BrandEdge>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type BrandEdge = {
  __typename: 'BrandEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: Brand;
};

export type BrandMembership = {
  __typename: 'BrandMembership';
  admin: Scalars['Boolean']['output'];
  brand: Brand;
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  invitationEmail?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  user?: Maybe<User>;
};

/** Autogenerated input type of CompleteProjectFileUpload */
export type CompleteProjectFileUploadInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  filename: Scalars['String']['input'];
  filepath: Scalars['String']['input'];
  filesize: Scalars['Int']['input'];
  filetype?: InputMaybe<Scalars['String']['input']>;
  projectId: Scalars['ID']['input'];
  url: Scalars['String']['input'];
};

/** Autogenerated return type of CompleteProjectFileUpload. */
export type CompleteProjectFileUploadPayload = {
  __typename: 'CompleteProjectFileUploadPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  projectFile: ProjectFile;
};

/** Autogenerated input type of CreateBrand */
export type CreateBrandInput = {
  brandAttributes: BrandAttributes;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateBrand. */
export type CreateBrandPayload = {
  __typename: 'CreateBrandPayload';
  brand: Brand;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of CreateProject */
export type CreateProjectInput = {
  brandId: Scalars['ID']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  projectAttributes: ProjectAttributes;
};

/** Autogenerated input type of CreateProjectLink */
export type CreateProjectLinkInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  projectId: Scalars['ID']['input'];
  projectLinkAttributes: ProjectLinkAttributes;
};

/** Autogenerated return type of CreateProjectLink. */
export type CreateProjectLinkPayload = {
  __typename: 'CreateProjectLinkPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  projectLink: ProjectLink;
};

/** Autogenerated return type of CreateProject. */
export type CreateProjectPayload = {
  __typename: 'CreateProjectPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  project: Project;
};

/** Autogenerated input type of CreateTagCategory */
export type CreateTagCategoryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  tagCategoryAttributes: TagCategoryAttributes;
};

/** Autogenerated return type of CreateTagCategory. */
export type CreateTagCategoryPayload = {
  __typename: 'CreateTagCategoryPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  tagCategory: TagCategory;
};

/** Autogenerated input type of CreateTag */
export type CreateTagInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  tagAttributes: TagAttributes;
};

/** Autogenerated return type of CreateTag. */
export type CreateTagPayload = {
  __typename: 'CreateTagPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  tag: Tag;
};

/** Autogenerated input type of DeleteBrandMembership */
export type DeleteBrandMembershipInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of DeleteBrandMembership. */
export type DeleteBrandMembershipPayload = {
  __typename: 'DeleteBrandMembershipPayload';
  brandMembership: BrandMembership;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of DeleteProjectFile */
export type DeleteProjectFileInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of DeleteProjectFile. */
export type DeleteProjectFilePayload = {
  __typename: 'DeleteProjectFilePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  projectFile: ProjectFile;
};

/** Autogenerated input type of DeleteProject */
export type DeleteProjectInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated input type of DeleteProjectLink */
export type DeleteProjectLinkInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of DeleteProjectLink. */
export type DeleteProjectLinkPayload = {
  __typename: 'DeleteProjectLinkPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  projectLink: ProjectLink;
};

/** Autogenerated return type of DeleteProject. */
export type DeleteProjectPayload = {
  __typename: 'DeleteProjectPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  project: Project;
};

/** Autogenerated input type of DeleteTagCategory */
export type DeleteTagCategoryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of DeleteTagCategory. */
export type DeleteTagCategoryPayload = {
  __typename: 'DeleteTagCategoryPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  tagCategory: TagCategory;
};

/** Autogenerated input type of DeleteTag */
export type DeleteTagInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of DeleteTag. */
export type DeleteTagPayload = {
  __typename: 'DeleteTagPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  tag: Tag;
};

/** Autogenerated input type of InviteBrandMember */
export type InviteBrandMemberInput = {
  admin: Scalars['Boolean']['input'];
  brandId: Scalars['ID']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  email: Scalars['String']['input'];
};

/** Autogenerated return type of InviteBrandMember. */
export type InviteBrandMemberPayload = {
  __typename: 'InviteBrandMemberPayload';
  brandMembership: BrandMembership;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

export type License = {
  __typename: 'License';
  dedicationHtml?: Maybe<Scalars['String']['output']>;
  discouraged: Scalars['Boolean']['output'];
  discouragedReason?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  logoUrl?: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

/** Autogenerated input type of MoveProjectFile */
export type MoveProjectFileInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  destinationIndex: Scalars['Int']['input'];
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of MoveProjectFile. */
export type MoveProjectFilePayload = {
  __typename: 'MoveProjectFilePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  project: Project;
  projectFile: ProjectFile;
};

/** Autogenerated input type of MoveProjectLink */
export type MoveProjectLinkInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  destinationIndex: Scalars['Int']['input'];
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of MoveProjectLink. */
export type MoveProjectLinkPayload = {
  __typename: 'MoveProjectLinkPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  project: Project;
  projectLink: ProjectLink;
};

export type Mutation = {
  __typename: 'Mutation';
  acceptBrandMembershipInvitation?: Maybe<AcceptBrandMembershipInvitationPayload>;
  approveBrand?: Maybe<ApproveBrandPayload>;
  completeProjectFileUpload?: Maybe<CompleteProjectFileUploadPayload>;
  createBrand?: Maybe<CreateBrandPayload>;
  createProject?: Maybe<CreateProjectPayload>;
  createProjectLink?: Maybe<CreateProjectLinkPayload>;
  createTag?: Maybe<CreateTagPayload>;
  createTagCategory?: Maybe<CreateTagCategoryPayload>;
  deleteBrandMembership?: Maybe<DeleteBrandMembershipPayload>;
  deleteProject?: Maybe<DeleteProjectPayload>;
  deleteProjectFile?: Maybe<DeleteProjectFilePayload>;
  deleteProjectLink?: Maybe<DeleteProjectLinkPayload>;
  deleteTag?: Maybe<DeleteTagPayload>;
  deleteTagCategory?: Maybe<DeleteTagCategoryPayload>;
  inviteBrandMember?: Maybe<InviteBrandMemberPayload>;
  moveProjectFile?: Maybe<MoveProjectFilePayload>;
  moveProjectLink?: Maybe<MoveProjectLinkPayload>;
  promoteProject?: Maybe<PromoteProjectPayload>;
  setReturnUrl?: Maybe<SetReturnUrlPayload>;
  unpromoteProject?: Maybe<UnpromoteProjectPayload>;
  updateBrand?: Maybe<UpdateBrandPayload>;
  updateProject?: Maybe<UpdateProjectPayload>;
  updateProjectLink?: Maybe<UpdateProjectLinkPayload>;
  updateTag?: Maybe<UpdateTagPayload>;
  updateTagCategory?: Maybe<UpdateTagCategoryPayload>;
};

export type MutationAcceptBrandMembershipInvitationArgs = {
  input: AcceptBrandMembershipInvitationInput;
};

export type MutationApproveBrandArgs = {
  input: ApproveBrandInput;
};

export type MutationCompleteProjectFileUploadArgs = {
  input: CompleteProjectFileUploadInput;
};

export type MutationCreateBrandArgs = {
  input: CreateBrandInput;
};

export type MutationCreateProjectArgs = {
  input: CreateProjectInput;
};

export type MutationCreateProjectLinkArgs = {
  input: CreateProjectLinkInput;
};

export type MutationCreateTagArgs = {
  input: CreateTagInput;
};

export type MutationCreateTagCategoryArgs = {
  input: CreateTagCategoryInput;
};

export type MutationDeleteBrandMembershipArgs = {
  input: DeleteBrandMembershipInput;
};

export type MutationDeleteProjectArgs = {
  input: DeleteProjectInput;
};

export type MutationDeleteProjectFileArgs = {
  input: DeleteProjectFileInput;
};

export type MutationDeleteProjectLinkArgs = {
  input: DeleteProjectLinkInput;
};

export type MutationDeleteTagArgs = {
  input: DeleteTagInput;
};

export type MutationDeleteTagCategoryArgs = {
  input: DeleteTagCategoryInput;
};

export type MutationInviteBrandMemberArgs = {
  input: InviteBrandMemberInput;
};

export type MutationMoveProjectFileArgs = {
  input: MoveProjectFileInput;
};

export type MutationMoveProjectLinkArgs = {
  input: MoveProjectLinkInput;
};

export type MutationPromoteProjectArgs = {
  input: PromoteProjectInput;
};

export type MutationSetReturnUrlArgs = {
  input: SetReturnUrlInput;
};

export type MutationUnpromoteProjectArgs = {
  input: UnpromoteProjectInput;
};

export type MutationUpdateBrandArgs = {
  input: UpdateBrandInput;
};

export type MutationUpdateProjectArgs = {
  input: UpdateProjectInput;
};

export type MutationUpdateProjectLinkArgs = {
  input: UpdateProjectLinkInput;
};

export type MutationUpdateTagArgs = {
  input: UpdateTagInput;
};

export type MutationUpdateTagCategoryArgs = {
  input: UpdateTagCategoryInput;
};

/** Information about pagination in a connection. */
export type PageInfo = {
  __typename: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['String']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['String']['output']>;
};

export type Project = {
  __typename: 'Project';
  authors?: Maybe<Scalars['String']['output']>;
  brand: Brand;
  createdAt: Scalars['ISO8601DateTime']['output'];
  currentUserCanDelete: Scalars['Boolean']['output'];
  currentUserCanDeleteFiles: Scalars['Boolean']['output'];
  currentUserCanEdit: Scalars['Boolean']['output'];
  currentUserCanUploadFiles: Scalars['Boolean']['output'];
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  lengthQuantity?: Maybe<Scalars['Int']['output']>;
  lengthUnits?: Maybe<Scalars['String']['output']>;
  license?: Maybe<License>;
  maxFacilitators?: Maybe<Scalars['Int']['output']>;
  maxPlayers?: Maybe<Scalars['Int']['output']>;
  minFacilitators?: Maybe<Scalars['Int']['output']>;
  minPlayers?: Maybe<Scalars['Int']['output']>;
  projectFiles: Array<ProjectFile>;
  projectLinks: Array<ProjectLink>;
  publicationYear?: Maybe<Scalars['Int']['output']>;
  tags: Array<Tag>;
  title?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type ProjectAttributes = {
  authors?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  lengthQuantity?: InputMaybe<Scalars['Int']['input']>;
  lengthUnits?: InputMaybe<Scalars['String']['input']>;
  licenseId?: InputMaybe<Scalars['ID']['input']>;
  maxFacilitators?: InputMaybe<Scalars['Int']['input']>;
  maxPlayers?: InputMaybe<Scalars['Int']['input']>;
  minFacilitators?: InputMaybe<Scalars['Int']['input']>;
  minPlayers?: InputMaybe<Scalars['Int']['input']>;
  publicationYear?: InputMaybe<Scalars['Int']['input']>;
  tagNames?: InputMaybe<Array<Scalars['String']['input']>>;
  title?: InputMaybe<Scalars['String']['input']>;
};

/** The connection type for Project. */
export type ProjectConnection = {
  __typename: 'ProjectConnection';
  /** A list of edges. */
  edges: Array<ProjectEdge>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type ProjectEdge = {
  __typename: 'ProjectEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: Project;
};

export type ProjectFile = {
  __typename: 'ProjectFile';
  createdAt: Scalars['ISO8601DateTime']['output'];
  filename: Scalars['String']['output'];
  filepath: Scalars['String']['output'];
  filesize: Scalars['Int']['output'];
  filetype?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  position: Scalars['Int']['output'];
  project: Project;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  uploaderId?: Maybe<Scalars['Int']['output']>;
  url: Scalars['String']['output'];
};

export type ProjectLink = {
  __typename: 'ProjectLink';
  icon?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  position: Scalars['Int']['output'];
  project: Project;
  title: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type ProjectLinkAttributes = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectPromotion = {
  __typename: 'ProjectPromotion';
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  project: Project;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** Autogenerated input type of PromoteProject */
export type PromoteProjectInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  projectId: Scalars['ID']['input'];
};

/** Autogenerated return type of PromoteProject. */
export type PromoteProjectPayload = {
  __typename: 'PromoteProjectPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  projectPromotion: ProjectPromotion;
};

export type Query = {
  __typename: 'Query';
  brand: Brand;
  brandMembership: BrandMembership;
  brands: BrandConnection;
  currentAbility: Ability;
  currentUser?: Maybe<User>;
  licenses: Array<License>;
  presignS3Url: Scalars['String']['output'];
  project: Project;
  projectPromotions: Array<ProjectPromotion>;
  projects: ProjectConnection;
  tag: Tag;
  tagByName?: Maybe<Tag>;
  tagCategories: TagCategoryConnection;
  tagCategory: TagCategory;
  tags: TagConnection;
};

export type QueryBrandArgs = {
  id?: InputMaybe<Scalars['ID']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
};

export type QueryBrandMembershipArgs = {
  brandId?: InputMaybe<Scalars['ID']['input']>;
  brandSlug?: InputMaybe<Scalars['String']['input']>;
  invitationToken: Scalars['String']['input'];
};

export type QueryBrandsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  unapproved?: InputMaybe<Scalars['Boolean']['input']>;
};

export type QueryPresignS3UrlArgs = {
  headers: Scalars['JSON']['input'];
  httpMethod: Scalars['String']['input'];
  url: Scalars['String']['input'];
};

export type QueryProjectArgs = {
  id: Scalars['ID']['input'];
};

export type QueryProjectsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  authors?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  brandId?: InputMaybe<Scalars['Int']['input']>;
  facilitatorCountLowerBound?: InputMaybe<Scalars['Int']['input']>;
  facilitatorCountUpperBound?: InputMaybe<Scalars['Int']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  playerCountLowerBound?: InputMaybe<Scalars['Int']['input']>;
  playerCountUpperBound?: InputMaybe<Scalars['Int']['input']>;
  queryString?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
};

export type QueryTagArgs = {
  id: Scalars['ID']['input'];
};

export type QueryTagByNameArgs = {
  name?: InputMaybe<Scalars['String']['input']>;
};

export type QueryTagCategoriesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  queryString?: InputMaybe<Scalars['String']['input']>;
};

export type QueryTagCategoryArgs = {
  id: Scalars['ID']['input'];
};

export type QueryTagsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  queryString?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated input type of SetReturnUrl */
export type SetReturnUrlInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  returnUrl: Scalars['String']['input'];
};

/** Autogenerated return type of SetReturnUrl. */
export type SetReturnUrlPayload = {
  __typename: 'SetReturnUrlPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

export type Tag = {
  __typename: 'Tag';
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  projects: ProjectConnection;
  tagCategory?: Maybe<TagCategory>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type TagProjectsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};

export type TagAttributes = {
  name?: InputMaybe<Scalars['String']['input']>;
  tagCategoryId?: InputMaybe<Scalars['ID']['input']>;
};

export type TagCategory = {
  __typename: 'TagCategory';
  color?: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  icon?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  tags: Array<Tag>;
  textColor?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type TagCategoryAttributes = {
  color?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

/** The connection type for TagCategory. */
export type TagCategoryConnection = {
  __typename: 'TagCategoryConnection';
  /** A list of edges. */
  edges: Array<TagCategoryEdge>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type TagCategoryEdge = {
  __typename: 'TagCategoryEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: TagCategory;
};

/** The connection type for Tag. */
export type TagConnection = {
  __typename: 'TagConnection';
  /** A list of edges. */
  edges: Array<TagEdge>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type TagEdge = {
  __typename: 'TagEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: Tag;
};

/** Autogenerated input type of UnpromoteProject */
export type UnpromoteProjectInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  projectId: Scalars['ID']['input'];
};

/** Autogenerated return type of UnpromoteProject. */
export type UnpromoteProjectPayload = {
  __typename: 'UnpromoteProjectPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  projectPromotion: ProjectPromotion;
};

/** Autogenerated input type of UpdateBrand */
export type UpdateBrandInput = {
  brandAttributes: BrandAttributes;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of UpdateBrand. */
export type UpdateBrandPayload = {
  __typename: 'UpdateBrandPayload';
  brand: Brand;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of UpdateProject */
export type UpdateProjectInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
  projectAttributes: ProjectAttributes;
};

/** Autogenerated input type of UpdateProjectLink */
export type UpdateProjectLinkInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
  projectLinkAttributes: ProjectLinkAttributes;
};

/** Autogenerated return type of UpdateProjectLink. */
export type UpdateProjectLinkPayload = {
  __typename: 'UpdateProjectLinkPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  projectLink: ProjectLink;
};

/** Autogenerated return type of UpdateProject. */
export type UpdateProjectPayload = {
  __typename: 'UpdateProjectPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  project: Project;
};

/** Autogenerated input type of UpdateTagCategory */
export type UpdateTagCategoryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
  tagCategoryAttributes: TagCategoryAttributes;
};

/** Autogenerated return type of UpdateTagCategory. */
export type UpdateTagCategoryPayload = {
  __typename: 'UpdateTagCategoryPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  tagCategory: TagCategory;
};

/** Autogenerated input type of UpdateTag */
export type UpdateTagInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
  tagAttributes: TagAttributes;
};

/** Autogenerated return type of UpdateTag. */
export type UpdateTagPayload = {
  __typename: 'UpdateTagPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  tag: Tag;
};

export type User = {
  __typename: 'User';
  admin?: Maybe<Scalars['Boolean']['output']>;
  brandMemberships: Array<BrandMembership>;
  brands: Array<Brand>;
  email?: Maybe<Scalars['String']['output']>;
  firstname?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  lastname?: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  username: Scalars['String']['output'];
};
